namespace Fireburst;

public enum VmaSuballocationType : uint
{
	VMA_SUBALLOCATION_TYPE_FREE = 0,
	VMA_SUBALLOCATION_TYPE_UNKNOWN = 1,
	VMA_SUBALLOCATION_TYPE_BUFFER = 2,
	VMA_SUBALLOCATION_TYPE_IMAGE_UNKNOWN = 3,
	VMA_SUBALLOCATION_TYPE_IMAGE_LINEAR = 4,
	VMA_SUBALLOCATION_TYPE_IMAGE_OPTIMAL = 5,
	VMA_SUBALLOCATION_TYPE_MAX_ENUM = 0x7fffffff
}

public enum VmaAllocationRequestType
{
	Normal = 0,
	UpperAddress = 1,
	EndOf1st = 2,
	EndOf2nd = 3
}

public enum VmaMemoryUsage : uint
{
	Unknown = 0,
	GPUOnly = 1,
	CPUOnly = 2,
	CPUtoGPU = 3,
	GPUtoCPU = 4,
	CPUCopy = 5,
	GPULazilyAllocated = 6,
	VMA_MEMORY_USAGE_MAX_ENUM = 0x7fffffff
}

public enum VMA_CACHE_OPERATION : uint
{
	VMA_CACHE_FLUSH = 0,
	VMA_CACHE_INVALIDATE = 1
}

public enum VmaAllocatorCreateFlagBits : uint
{
	VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT = 0x1,
	VMA_ALLOCATOR_CREATE_KHR_DEDICATED_ALLOCATION_BIT = 0x2,
	VMA_ALLOCATOR_CREATE_KHR_BIND_MEMORY2BIT = 0x4,
	VMA_ALLOCATOR_CREATE_EXT_MEMORY_BUDGET_BIT = 0x8,
	VMA_ALLOCATOR_CREATE_AMD_DEVICE_COHERENT_MEMORY_BIT = 0x10,
	VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT = 0x20,
	VMA_ALLOCATOR_CREATE_EXT_MEMORY_PRIORITY_BIT = 0x40,
	VMA_ALLOCATOR_CREATE_FLAG_BITS_MAX_ENUM = 0x7fffffff
}

public enum VmaRecordFlagBits : uint
{
	VMA_RECORD_FLUSH_AFTER_CALL_BIT = 0x1,
	VMA_RECORD_FLAG_BITS_MAX_ENUM = 0x7fffffff
}

public enum VmaAllocationCreateFlags : uint
{
	DedicatedMemory = 0x1,
	NeverAllocate = 0x2,
	Mapped = 0x4,
	VMA_ALLOCATION_CREATE_CAN_BECOME_LOST_BIT = 0x8,
	VMA_ALLOCATION_CREATE_CAN_MAKE_OTHER_LOST_BIT = 0x10,
	VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT = 0x20,
	VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT = 0x40,
	VMA_ALLOCATION_CREATE_DONT_BIND_BIT = 0x80,
	VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT = 0x100,
	VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT = 0x10000,
	VMA_ALLOCATION_CREATE_STRATEGY_WORST_FIT_BIT = 0x20000,
	VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT = 0x40000,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT = 65536,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT = 262144,
	VMA_ALLOCATION_CREATE_STRATEGY_MIN_FRAGMENTATION_BIT = 131072,
	VMA_ALLOCATION_CREATE_STRATEGY_MASK = 458752,
	VMA_ALLOCATION_CREATE_FLAG_BITS_MAX_ENUM = 0x7fffffff
}

public enum VmaPoolCreateFlagBits : uint
{
	VMA_POOL_CREATE_IGNORE_BUFFER_IMAGE_GRANULARITY_BIT = 0x2,
	VMA_POOL_CREATE_LINEAR_ALGORITHM_BIT = 0x4,
	VMA_POOL_CREATE_BUDDY_ALGORITHM_BIT = 0x8,
	VMA_POOL_CREATE_ALGORITHM_MASK = 12,
	VMA_POOL_CREATE_FLAG_BITS_MAX_ENUM = 0x7fffffff
}

public enum VmaDefragmentationFlagBits : uint
{
	VMA_DEFRAGMENTATION_FLAG_INCREMENTAL = 0x1,
	VMA_DEFRAGMENTATION_FLAG_BITS_MAX_ENUM = 0x7fffffff
}